### ISSUE TITLE
UI enhancements

### ISSUE THREAD

**Issue by M4Yt** [PilatusDevs/StatusPilatus#53]
#52 caused a couple of inconsistencies. I have some enhancements I want to do myself as well. Please comment any changes you still want to see in the UI in this issue. @Jelmerro @MeesMaas

**Comment by Jelmerro** [comment]
I don't have any big issues with it which weren't there before the migration. That being said, I do want to have the inconsistencies fixed with fields like this: `50MB` vs `50 MB`. I think they should all have a space between them. If you don't want this fix this as part of the UI enhancements I will make a separate issue for it.
